name: Visual Studio 2022

on:
  workflow_call:
    inputs:
      submodules:
        required: false
        type: string
        default: ''

      architecture:
        required: true
        type: string

      configuration:
        required: true
        type: string

      solution:
        required: true
        type: string

      cpu_count:
        required: false
        type: number
        default: 16

      output_file:
        required: true
        type: string

      output_extensions:
        required: true
        type: string

      artifact_name:
        required: false
        type: string
        default: ''

      upload_pdb:
        required: false
        type: boolean
        default: false

      pre_build_script:
        required: false
        type: string
        default: ''

      required_artifacts:
        required: false
        type: string
        default: ''

      required_artifacts_path:
        required: false
        type: string
        default: ''

jobs:
  build_vs_project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.submodules }}

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{ inputs.architecture }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.required_artifacts }}
          path: ${{ inputs.required_artifacts_path }}
        if: ${{ inputs.required_artifacts != '' &&  inputs.required_artifacts_path != '' }}

      - name: post build script
        run: |
          Add-Content -Path .\gh_pre_build_script..ps1 "${{ inputs.pre_build_script }}"
          .\gh_pre_build_script..ps1
          Remove-Item .\gh_pre_build_script..ps1
        if: ${{ inputs.pre_build_script != '' }}

      - name: Compile
        run: MSBuild.exe /p:Configuration=${{ inputs.configuration }} /p:Platform=${{ inputs.architecture }} /maxcpucount:${{ inputs.cpu_count }} "${{ inputs.solution }}"

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name != '' && inputs.artifact_name || inputs.output_file }}
          path: build/${{ inputs.configuration }}-${{ inputs.architecture }}/${{ inputs.output_file }}.${{ inputs.output_extensions }}

      - name: Upload compiled pdb file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name != '' && inputs.artifact_name || inputs.output_file }}.pdb
          path: build/${{ inputs.configuration }}-${{ inputs.architecture }}/${{ inputs.output_file }}.pdb
        if: ${{ inputs.upload_pdb }}
