on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string

      configuration:
        required: true
        type: string

      solution:
        required: true
        type: string

      cpu_count:
        required: false
        type: number
        default: 16

      output_file:
        required: true
        type: string

      output_pdb_file:
        required: false
        type: string

      upload_pdb:
        required: false
        type: boolean
        default: false

jobs:
  build_vs_project:
    name: Build Visual Studio project
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{ inputs.architecture }}

      - name: Compile
        run: MSBuild.exe /p:Configuration=${{ inputs.configuration }} /p:Platform=${{ inputs.architecture }} /maxcpucount:${{ inputs.cpu_count }} "${{ inputs.solution }}"

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.output_file }}
          path: build/${{ inputs.configuration }}-${{ inputs.architecture }}/${{ inputs.output_file }}

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.output_pdb_file }}
          path: build/${{ inputs.configuration }}-${{ inputs.architecture }}/${{ inputs.output_pdb_file }}
        if: ${{ inputs.upload_pdb }}
